// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS3ag10hEjTRK-_DL5Rk3TbhS1MiMV9Pg',
    appId: '1:846522112191:android:c38d5f6e3243e1d4374e0a',
    messagingSenderId: '846522112191',
    projectId: 'tekmob-66ff6',
    storageBucket: 'tekmob-66ff6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcGkosBrXrcnmRfMbIQ4eAKwtWgNRgPhw',
    appId: '1:846522112191:ios:4ed495f2e89198bf374e0a',
    messagingSenderId: '846522112191',
    projectId: 'tekmob-66ff6',
    storageBucket: 'tekmob-66ff6.firebasestorage.app',
    iosClientId: '846522112191-r59152ihpf2ld3kqn34u2pufc1ind0o3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZfcRQouWDmuTw9wxIp48gzQqc4sLvttU',
    appId: '1:846522112191:web:02abe396f2aff1cc374e0a',
    messagingSenderId: '846522112191',
    projectId: 'tekmob-66ff6',
    authDomain: 'tekmob-66ff6.firebaseapp.com',
    storageBucket: 'tekmob-66ff6.firebasestorage.app',
    measurementId: 'G-H7258JY344',
  );

}