name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  google_sign_in: ^6.1.0
  cupertino_icons: ^1.0.8

  flutter_localizations:
    sdk: flutter

  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/google_logo.png
